### ISSUE TITLE
Add path to folder with proto files

### ISSUE THREAD

**Issue by istudyatuni** [eliaperantoni/spaceman#2]
As title says, it would be useful to specify just path to folder with .proto files. Or maybe a way to specify multiple files

**Comment by eliaperantoni** [comment]
Wait, are you saying Spaceman should work with text `.proto` files?

Spaceman expects compiled Protobuf descriptor files (the ones written to whatever path you passed to `protoc -o <...>`), not `.proto` uncompiled source Protobuf files which, AFAIK, only the [JavaScript SDK](https://www.npmjs.com/package/@grpc/proto-loader) can handle directly. Most non-JS applications that I've seen rely on calling `protoc` on the user's computer, there are also [pure Rust solutions](https://github.com/andrewhickman/protox) but they both seem a little fragile to me as you need to make sure that the import paths are correct and you are assuming that the necessary software is installed.

If the issue is about specifying multiple files with a single entry instead, what about a glob? Like `/proto/*` would import all Protobuf descriptor files under the `/proto` directory.

**Comment by istudyatuni** [comment]
Oh, my bad, didn't understand, that it should work with compiled description. Saw this only in `playground`. About glob - also useful information! Thanks, now it works!

**Comment by eliaperantoni** [comment]
No problem! The readme definitely does a bad job at explaining that, I should fix that. For the globs: that isn't actually implemented yet, I was only proposing a different solution for importing different files at once.

**Comment by istudyatuni** [comment]
Oh, okay. I'm using https://github.com/bufbuild/buf, it could export multiple files to single .desc file:

```sh
buf build -o api.desc --as-file-descriptor-set
```
